kodadot/stick

package-lock.json
package.json
src/mappings/uniques/mint.ts
src/mappings/uniques/setMetadata.ts

- :arrow_up: @kodadot1/minipfs
- :zap: early return for non-metadata
- :zap: fallback to collection metadata if available

New Metadata

---

package-lock.json
package.json
src/server-extension/model/count.model.ts
src/server-extension/model/event.model.ts
src/server-extension/model/series.model.ts
src/server-extension/model/spotlight.model.ts
src/server-extension/query/activeWallets.ts
src/server-extension/query/event.ts
src/server-extension/resolvers/collectionEvent.ts
src/server-extension/resolvers/event.ts
src/server-extension/resolvers/index.ts
src/server-extension/resolvers/series.ts
src/server-extension/resolvers/spotlight.ts
src/server-extension/resolvers/walletResolver.ts
src/server-extension/utils.ts

- :heavy_plus_sign: type-graphql
- :tada: resolvers

resolveeers

---

.github/workflows/subsquid.yml

**Thank you for your contribution** to the [KodaDot Indexer](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

feat: Add deploy workflow

---

squid.yaml

bump version

---

src/mappings/nfts/setAttribute.ts
src/mappings/uniques/setAttribute.ts
src/mappings/uniques/types.ts

- :bug: improper handling of empty array
- :bug: display should be empty_string instead of undefined string

37 unttribute

---

README.md
src/types/statemine/events.ts
src/types/statemine/storage.ts
src/types/statemine/support.ts
src/types/statemine/v1.ts
src/types/statemine/v9230.ts
src/types/statemine/v9420.ts
src/types/statemine/v9430.ts

- :squid: typegen
- :memo: squid:log

:label: Statemine types

---

Makefile
db/migrations/1693998172302-Data.js
schema.graphql
src/model/generated/collectionEntity.model.ts
src/model/generated/nftEntity.model.ts

- close #97 
- close #96 
today I learned blocknumber isn't unique by collectionEnitity

🔧 entity index

---

src/server-extension/query/tokenEntities.ts
src/server-extension/query/totalTokenEntities.ts
src/server-extension/resolvers/tokenEntities.ts
src/server-extension/resolvers/totalTokenEntities.ts

Profile page needs abilty to filter token entites by issuer (created tab)
add it to resolvers

allow filter by issuer

---

src/server-extension/query/tokenEntities.ts
src/server-extension/query/totalTokenEntities.ts
src/server-extension/resolvers/tokenEntities.ts
src/server-extension/resolvers/totalTokenEntities.ts

* https://github.com/kodadot/nft-gallery/issues/7705

Enable free string search

---

src/server-extension/query/tokenEntities.ts
src/server-extension/query/totalTokenEntities.ts
src/server-extension/resolvers/tokenEntities.ts
src/server-extension/resolvers/totalTokenEntities.ts

https://github.com/kodadot/stick/pull/121

🔖  Speck v5.1.2

---

src/server-extension/query/tokenEntities.ts
src/server-extension/query/totalTokenEntities.ts
src/server-extension/resolvers/tokenEntities.ts
src/server-extension/resolvers/totalTokenEntities.ts

https://github.com/kodadot/stick/pull/121

🔖  Stick v5.1.2

---

src/mappings/shared/metadata.ts
src/mappings/utils/types.ts

could it be as simple as this?

attributes

---

.gitignore
src/mappings/nfts/getters/statemine.ts
src/mappings/nfts/getters/statemint.ts
src/mappings/utils/helper.ts

- :see_no_evil: .vscode
- :bug: The expression evaluated to a falsy value: (0, assert_1.default)(isHex(value))
- :bug: CHANGEISSUER cannot process because of empty address value

(Fix): CHANGEISSUER cannot proceed

---

speck.yaml

- #138 
cc @daiagi @roiLeo 
This will make new speck v7.
Once it is indexed i had to manually switch the `[prod]` button

🔖 Speck V7

---

src/mappings/shared/token/tokenAPI.ts
src/mappings/shared/token/utils.ts

exclude names from token naming rule

---

src/environment.ts
src/mappings/nfts/buy.ts
src/mappings/nfts/list.ts
src/types/statemine/events.ts

What's missing:
- ownercount
- distribution
will do the rest latter, feel free to commit on this branch

🔧 collection handlelist and handlebuy

---

.github/workflows/update.yml

:construction_worker: Viki the devops

---

db/migrations/1700144394115-Data.js
schema.graphql
src/mappings/nfts/mint.ts
src/model/generated/collectionEntity.model.ts

- :alien: collection global royalty
- :squid: collection global royalty
- :zap: set royalty if present in collection

Global royalty per collectiom

---

src/mappings/uniques/buy.ts

- ref https://github.com/kodadot/nft-gallery/pull/8588#issuecomment-1857813575
- link #143

🔧 unique handlebuy volume

---

src/mappings/nfts/burn.ts
src/mappings/uniques/burn.ts

🔧 update entity on burn

---

src/mappings/nfts/burn.ts
src/mappings/nfts/buy.ts
src/mappings/nfts/list.ts
src/mappings/nfts/transfer.ts
src/mappings/uniques/burn.ts
src/mappings/uniques/buy.ts
src/mappings/uniques/list.ts
src/mappings/uniques/transfer.ts

- goes after #167 
- close #166
- close #142

🔧 save collection context

---

package.json
speck.yaml
squid.yaml

- https://github.com/kodadot/stick/pull/165#issuecomment-1879685553

🚀 release new squid version

---

src/mappings/nfts/setMetadata.ts
src/mappings/uniques/setMetadata.ts

🔧 save metadata

---

README.md

I killed the squid and redeploying again
Close #189

🔖  Speck v10

---

src/mappings/nfts/mint.ts
src/mappings/uniques/mint.ts

- #133 
revert all my changes 😦

🔧 mint send_to

---

polkadot.json
src/environment.ts
src/mappings/assets/create.ts
src/mappings/assets/forceCreate.ts
src/mappings/assets/forceToken.ts
src/mappings/assets/getters/index.ts
src/mappings/assets/getters/kusama.ts
src/mappings/assets/getters/polkadot.ts
src/mappings/assets/index.ts
src/mappings/assets/setMetadata.ts
src/mappings/assets/types.ts
src/mappings/index.ts
src/processable.ts
src/processor.ts
src/types/kusama/assets/events.ts
src/types/kusama/events.ts
src/types/kusama/v1.ts
src/types/polkadot/assets/events.ts
src/types/polkadot/events.ts
typegen.json

- :squid: typegen for assets
- :squid: TYPEGEN
- :squid: TYPEGEN
- :squid: TYPEGEN On events
- :squid: Typegen final
- :wave: Asset
- :zap: enable metadata set
- :broom: imports
- :tada: getters for assets
- :tada: assets
- :zap: register assets
- :label: Chain type
- :zap: new ops
- :wrench: Start block
- :zap: force create tokens

very nice assets

---

.eslintrc
package.json
scripts/sub-client.js
src/mappings/assets/forceToken.ts
src/mappings/index.ts
src/mappings/nfts/getters/index.ts
src/mappings/utils/cache.ts

🔧 lint code

---

src/mappings/shared/token/tokenAPI.ts
src/mappings/shared/token/utils.ts

retry delete token entity up to 3 times
don't panic in case of failure

retry delete token, don't panic

---

.github/workflows/subsquid.yml
src/mappings/shared/token/tokenAPI.ts
src/mappings/shared/token/utils.ts

- **Update subsquid.yml**
- **retry delete token**
- **simple try/catch**

:bookmark: Stick fix

---

README.md

- **:zap: use db count for removing**
- **:technologist: less variables**
- **Update subsquid.yml**
- **retry delete token**
- **simple try/catch**

:bookmark: Speck v10

---

src/mappings/shared/token/burn.ts

i didn't notice that burn events nft is not being unlinked from token
quite likely to be the source of bug
have to deploy to test because it never happens on my local

pass burn through tokenApi handler

---

db/migrations/1711017751137-Data.js
schema.graphql
src/mappings/shared/token/tokenAPI.ts
src/model/generated/tokenEntity.model.ts
src/server-extension/query/tokenEntities.ts
src/server-extension/query/totalTokenEntities.ts

this is a cop-out solution
instead of deleting token entity, we mark them and filter out in the resolver

avoid deletion

---

db/migrations/1719489409922-Data.js

:card_file_box: base_uri

---

src/mappings/nfts/setAttribute.ts
src/mappings/utils/helper.ts

Based on the log
```
15:12:51 DEBUG squid:log [setAttribute] {
"classId": 146,
"instanceId": 272,
"key": "0x726563697069656e74",
"value": "0x313669614d6959447479343259447a755064707657424136594458655a37655868626935626132646f774e5776444539",
"human": {
"key": "recipient",
"value": "16iaMiYDty42YDzuPdpvWBA6YDXeZ7eXhbi5ba2dowNWvDE9"
}
}
AssertionError [ERR_ASSERTION]: invalid address length
at Object.encode
generatedMessage: false,
code: 'ERR_ASSERTION',
actual: false,
expected: true,
operator: '=='
}
```

:zap: proper way to address address :D

---

src/mappings/nfts/create.ts
src/mappings/uniques/create.ts

:bug: kind not applied to collection entity

---

src/server-extension/query/tokenEntities.ts

related to https://github.com/kodadot/nft-gallery/issues/10991#issuecomment-2365167466
TBH I don't know if it could fix the issue or not. I didn't run the project locally but it's the only mistake I found. cc @vikiival

fix: syntax error

---

src/mappings/nfts/buy.ts
src/mappings/nfts/list.ts
src/mappings/nfts/mint.ts
src/mappings/nfts/transfer.ts
src/mappings/uniques/buy.ts
src/mappings/uniques/list.ts
src/mappings/uniques/mint.ts
src/mappings/uniques/transfer.ts

fix: unlisted nfts are saved as `0` not `NULL`

---

src/server-extension/query/totalTokenEntities.ts
src/server-extension/resolvers/totalTokenEntities.ts

related to https://github.com/kodadot/nft-gallery/issues/10991
add `kind` query to the resolver `tokenEntityCount`.
I have not run the code locally, so may need your help to review and check. cc @vikiival

feat: count of art kind

---

src/server-extension/query/totalTokenEntities.ts

fix 
related to https://github.com/kodadot/stick/pull/317

fix: kind count

---

src/mappings/nfts/setMetadata.ts

fix: collection kind

---

src/mappings/nfts/mint.ts
src/mappings/utils/types.ts
src/processor.ts

- related with #299 
- store initial mint price in `MINT` event

🔧 mint call amount args

---

src/mappings/nfts/claimSwap.ts

- might fix kodadot/nft-gallery#11550

🔧 Claim Swap increase volume
